### ISSUE TITLE
Performance  problem

### ISSUE THREAD

**Issue by zxdong262** [tylerlong/react-subx#1]
Experienced serious performance problem, so I changed to use customized react-subx to solve it,  modify it like this:
```js
constructor(props = {})
...
const { result, stream$ } = SubX.runAndMonitor(props.store || SubX.create(props), render)
```
Not sure the root cause, but it do works.

**Comment by tylerlong** [comment]
Appreciate if you could provide me with a simple React application to reproduce the performance issue.
